### ISSUE TITLE
[feat] Auto fetch from old.openzwave/downloads

### ISSUE THREAD

**Issue by robertsLando** [OpenZWave/openzwave-docker#43]
By using [pup](https://github.com/ericchiang/pup) command line tool we could easily build a script that automatically parse the version from http://old.openzwave.com/downloads/

Example: 

```bash
curl -s http://old.openzwave.com/downloads/ | pup '#pagecontent > table:nth-child(2) > tbody > tr:nth-child(2) > td:nth-child(1) text{}'
curl -s http://old.openzwave.com/downloads/ | pup '#pagecontent > table:nth-child(2) > tbody > tr:nth-child(3) > td:nth-child(1) text{}'
curl -s http://old.openzwave.com/downloads/ | pup '#pagecontent > table:nth-child(2) > tbody > tr:nth-child(4) > td:nth-child(1) text{}'
```

Output:

```
 1.6.1382
 1.6.1280
 1.6.1240
```

Draft code:

```
wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
unzip pup_v0.4.0_linux_amd64.zip

wget http://old.openzwave.com/downloads/ -O downloads.html
VERSION1=$(cat downloads.html | ./pup '#pagecontent > table:nth-child(2) > tbody > tr:nth-child(2) > td:nth-child(1) text{}')
VERSION2=$(cat downloads.html | ./pup '#pagecontent > table:nth-child(2) > tbody > tr:nth-child(3) > td:nth-child(1) text{}')
VERSION3=$(cat downloads.html | ./pup '#pagecontent > table:nth-child(2) > tbody > tr:nth-child(4) > td:nth-child(1) text{}')
```

And we could add a dynamic matrix in this way: https://stackoverflow.com/questions/59977364/github-actions-how-use-strategy-matrix-with-script

**Comment by chrisns** [comment]
ooh, yeah that'd be neat. just need to figure the thing to trigger it I guess

**Comment by robertsLando** [comment]
Scheduled :) 

---

Daniel

**Comment by robertsLando** [comment]
I would add the matrix to a file, and compare that file to the new one using diff command

**Comment by chrisns** [comment]
yeah that'd work 👍

**Comment by robertsLando** [comment]
> The workflow is not valid. .github/workflows/dockerbuild.yml (Line: 37, Col: 9): Unrecognized named-value: 'matrix'. Located at position 11 within expression: !contains(matrix.dockerfile + '-'  + matrix.openzwave, needs.matrix.outputs.tags)

**Comment by robertsLando** [comment]
@chrisns Seems good but I don't understand why there are 2 scheduled builds: https://github.com/OpenZWave/openzwave-docker/actions

**Comment by chrisns** [comment]
err think your cron syntax is out, currently looks like it runs every minute on the 0 hour, will pr it

**Comment by robertsLando** [comment]
Sorry :confounded:

**Comment by chrisns** [comment]
> Sorry 😖

no problem, means i'm one pr closer to #hacktoberfest tshirt :)
