### ISSUE TITLE
broke my own my access!

### ISSUE THREAD

**Issue by chrisns** [OpenZWave/openzwave-docker#7]
Hi @Fishwaldo, please help! I transferred this repo into the org, but in the process have lost my own access/ownership of the repo! 🤦

**Comment by robertsLando** [comment]
I can't help @chrisns I don't have the permissions too

**Comment by Fishwaldo** [comment]
Sorry - missed this - You had access, but I've re-added you. Try again.

**Comment by chrisns** [comment]
ace, thanks @Fishwaldo all sorted now!
